openapi: 3.0.3
info:
  title: GetEmpStatus API
  version: 1.0.0
paths:
  /api/GetEmpStatus:
    post:
      summary: Compute employee status by NationalNumber
      security:
        - ApiTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [NationalNumber]
              properties:
                NationalNumber:
                  type: string
                  example: NAT1001
      responses:
        '200':
          description: Computed status
          content:
            application/json:
              schema:
                type: object
        '401': { description: Unauthorized }
        '404': { description: Invalid National Number }
        '406': { description: User is not Active }
        '422': { description: INSUFFICIENT_DATA }
components:
  securitySchemes:
    ApiTokenAuth:
      type: apiKey
      in: header
      name: x-api-token
